### ISSUE TITLE
cannot import name '_DaliBaseIterator' from 'nvidia.dali'

### ISSUE THREAD

**Issue by bucky999** [ShiqiYu/libfacedetection.train#34]
安装了nvidia-dali-cuda102==1.5.0 和nvidia-dali-tf-plugin-cuda102==1.5.0 
运行python train.py 
报错如下：
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from data import get_train_loader
  File "/app/code/face_recognition/libface/libfacedetection.train/tasks/task1/../../src/data.py", line 11, in <module>
    from nvidia.dali import _DaliBaseIterator
ImportError: cannot import name '_DaliBaseIterator' from 'nvidia.dali' (/root/anaconda3/envs/libface/lib/python3.7/site-packages/nvidia/dali/__init__.py)

**Comment by bucky999** [comment]
已经解决 感谢
